### ISSUE TITLE
strict argument parsing for leaf-list `min-elements` incompatible with some IETF models

### ISSUE THREAD

**Issue by william-tremblay1** [freeconf/gconf#114]
IETF models [ietf-l3vpn-svc](https://github.com/YangModels/yang/blob/main/standard/ietf/RFC/ietf-l3vpn-svc%402018-01-19.yang) and [ietf-routing](https://github.com/YangModels/yang/blob/main/standard/ietf/RFC/ietf-routing%402018-03-13.yang) use a string as the value of the leaf-list `min-elements` key, i.e. `min-elements "1"` instead of `min elements 1`. Pyang accepts this, but the freeconf parser doesn't. [RFC 7950](https://datatracker.ietf.org/doc/html/rfc7950#section-14) seems ambiguous about it, using `< a string that matches the rule >`  

```
  min-elements-stmt   = min-elements-keyword sep
                         min-value-arg-str stmtend

   min-value-arg-str   = < a string that matches the rule >
                         < min-value-arg >

   min-value-arg       = non-negative-integer-value
```

Although there were no instances of IETF models using `max-elements` with a string argument, I suspect a similar inconsistency would be present there.

**Comment by dhubler** [comment]
Likely freeconf issue but easy fix I can look into

**Comment by dhubler** [comment]
should be fixed in HEAD.  other repos like restconf will eventually be updated
