### ISSUE TITLE
Locking data structures for read access

### ISSUE THREAD

**Issue by HRogge** [freeconf/gconf#30]
How is the "standard" way to lock data structures for read access. As far as I can see we have BeginEdit() and EndEdit() to lock a write access, but this doesn't help with reading.

An alternative would be a transfer of all restconf operations to a go-routine of the users choice.

**Comment by dhubler** [comment]
You are right, there is no current way for read but I would suggest we add
to this interface:


***@***.***/node#Trigger

We just need to add read.  This would be more elegant that overriding each
and every Node interface

**Comment by HRogge** [comment]
first time I look at this file (trigger.go)... do you have an example how this code is used together with yang/restconf?

**Comment by dhubler** [comment]
I don't have any examples, but Browser has a TriggerTable, and you call
Install with a Trigger to intercept each call.  I think we'd have to make
it more efficient if we wanted to intercept every read

**Comment by dhubler** [comment]
closing.  reopen if you see something

**Comment by HRogge** [comment]
Hi, I am finally back working on our Restconf code and still hitting the same issue.

I think my trouble I have comes from the issue that the Restconf API forces a "hidden" go-routine into my code, which makes synchronization quite difficult.

Is it possible to run the restconf API with an already http.Server instance, just handing off the routed serveHttp() call into the API? This way it would be quite easy to lock down the data structures before calling into the library code and then unlocking them when restconf has handled the http-call.

**Comment by dhubler** [comment]
Welcome back!

You should be able to pass this into Go's web server as a handler
  https://github.com/freeconf/restconf/blob/master/server.go#L118

**Comment by HRogge** [comment]
Hmm... is there a way to generate a restconf.Server instance without having an "fc-restconf" module attached to it? Because the fc-restconf node is always one step away from spawning its own http-server if I see it correctly.

**Comment by dhubler** [comment]
Adding Server functionality to an external web service is definitely
something that would be useful to others.  If you fork restconf and add a
new constructor parallel to NewServer except it doesn't do the things you
don't want it do, we can start from there.

**Comment by HRogge** [comment]
I will look into it...
