### ISSUE TITLE
JSON namespace-qualified names not supported

### ISSUE THREAD

**Issue by tdecorte123** [freeconf/gconf#33]
Hi, I'm experimenting with these nice libraries by writing a prototype restconf server for some custom yang models.

It works fine except when my querie contains namespace prefixes. Looking at the yang library, it seems that namespaces are not supported... Except for a compatibility mode used in the JSON writer but not when parsing JSON body queries.

Is this correct or am I missing something somewhere?

Thx

**Comment by dhubler** [comment]
It should be supported for parsing JSON bodies as well.  This is new so
there might be a bug.  Can you construct a failed unit test or provide some
more info?

**Comment by tdecorte123** [comment]
Hi, thx for the reply.

In a nutshell, I have an identityref leaf using a derived type defined in an imported yang module. When processing the leaf, this code:
func toIdentRef(base *meta.Identity, v interface{}) (val.IdentRef, error) {
	var empty val.IdentRef
	x := fmt.Sprintf("%v", v)
	ref, found := base.Derived()[x]
//...
}

compares namespace-qualified name receive in the JSON with the derived type name without the namespace. In other words it compares A:B with B. Which fails. If I remove the namespace from the JSON body, it works fine.

I can provide a small example if needed.

Thx

**Comment by tdecorte123** [comment]
Hi,

A quick and dirty example that will panic at startup:

[main.go.txt](https://github.com/freeconf/yang/files/10287848/main.go.txt)
[Module-test.yang.txt](https://github.com/freeconf/yang/files/10287849/Module-test.yang.txt)
[Module-types.yang.txt](https://github.com/freeconf/yang/files/10287850/Module-types.yang.txt)

If you remove the namespace ("type":"derived-type") it works... But when getting back the "type" leaf you get this result:
GET http://localhost:8090/restconf/data/Module-test
{
    "Module-test:type": "derived-type"
}

Here the namespace is applied to the key and not the value which is incorrect as far as I know. type doesn't require a namspace since it's already in Module-test namespace and the derived type needs to be prefixed.

As a reference, section 6.8 of RFC7951.

Thx

**Comment by dhubler** [comment]
I was able to duplicate this and spec reference confirms your assertion.  I should have fix and unit test in next couple days, thanks for reporting!
