### ISSUE TITLE
'import' and 'include' statements are not supporting 'revision-date' sub statement

### ISSUE THREAD

**Issue by davidmat50** [freeconf/gconf#36]
As per RFC 7950,  'import' and 'inlcude' statements should support 'revision-date' sub statement.
But i see that  'revision' is  supported instead of revision-date  for import and include statements. 

RFC reference:
https://www.rfc-editor.org/rfc/rfc7950#section-7.1.5
https://www.rfc-editor.org/rfc/rfc7950#section-7.1.5.1
https://www.rfc-editor.org/rfc/rfc7950#section-7.1.6

**Comment by dhubler** [comment]
hot dog!  I'm on it! thanks for reporting and the succinct description.

**Comment by dhubler** [comment]
closing this because parser doesn't bail.  opened #40 to support file naming scheme.
