### ISSUE TITLE
'pattern' does not support 'modifier' substatement

### ISSUE THREAD

**Issue by davidmat50** [freeconf/gconf#37]
As per RFC 7950,  pattern statement should support 'modifier' sub-statement in it.  
https://www.rfc-editor.org/rfc/rfc7950#section-9.4.5.1
https://www.rfc-editor.org/rfc/rfc7950#section-9.4.6

but freeconf/uang library is not suuporting 'modifier' while loading yang modules.

**Comment by dhubler** [comment]
oh neat! I missed that.  no problem.

**Comment by dhubler** [comment]
please re-open if master branch doesn't work for you now.

**Comment by davidmat50** [comment]
This issue still exists. 
The yang module loading is failing if modifier and 'invert-match' keywords are present. 

example:

               pattern '[Ii][Nn][Tt][Ee][Rr][Nn][Ee][Tt]$' { // mesh-tag with value="INTERNET" cannot be created
                    modifier invert-match;
                    error-message "Mesh-tag 'INTERNET' already exist and cannot be created.";
                }
