### ISSUE TITLE
Error while loading augment with augment string as mentioned in RFC7950 

### ISSUE THREAD

**Issue by davidmat50** [freeconf/gconf#39]
reference:
https://www.rfc-editor.org/rfc/rfc7950#section-7.17.3

As per athe above section in RFC,  ( augment "/if:interfaces/if:ifEntry"  ) should be supported,  but we get error.
Error:  augment target is not found /if:interfaces/if:ifEntry

But if use the augment string as  ( augment "/if:interfaces/ifEntry"), loading of module is success. 

Please  support  ( augment "/if:interfaces/if:ifEntry"  ) also as mentioned in RFC.

**Comment by dhubler** [comment]
fixed
