### ISSUE TITLE
'pattern' does not support 'modifier' substatement along with 'error-message' substatement

### ISSUE THREAD

**Issue by davidmat50** [freeconf/gconf#41]
The issue raised in https://github.com/freeconf/yang/issues/37  is still present 
The yang module loading is failing if modifier and 'invert-match' keywords are present.

example:

                pattern '[Ii][Nn][Tt][Ee][Rr][Nn][Ee][Tt]$' { // mesh-tag with value="INTERNET" cannot be created
                    modifier invert-match;
                    error-message "Mesh-tag 'INTERNET' already exist and cannot be created.";
                }

**Comment by davidmat50** [comment]
Oh sorry.   I have noticed that  modifier invert-match is supported,  but the loading fails when  both 'modifier'  and 'error-message'  are present together as substatements for pattern.

If only one of the substatement is present under 'pattern', then yang loading is succesful

**Comment by dhubler** [comment]
ok, i did not test that and i can see i got the grammar too limited

grammar:
  https://github.com/freeconf/yang/blob/master/parser/parser.y#L834

test case

https://github.com/freeconf/yang/blob/master/parser/testdata/types/leaf.yang#L34

should be easy fix, I can get this in next day or so.

**Comment by dhubler** [comment]
should be all set now on master
