### ISSUE TITLE
Yang loading  is failing if default substatement is added for leaf of type enum where enum name starts as a number.

### ISSUE THREAD

**Issue by davidmat50** [freeconf/gconf#42]
Not able to add default substatment in leaf if the enum looks like below. 
(please note the enum name startes with number) 

    leaf mybytes {
        type enumeration {
            enum 4k;
            enum 8k {
                value 8192;
            }
            enum 12k {
                value 12288;
            }
            enum 16k {
                value 16384;
            }
        }
        default 16k;
     }

But the yang loading is working fine(below)   when default substatment is added with similar enum where enum name does not start as number digits.

    leaf myenum {
        type enumeration {
            enum zero;
            enum one;
            enum two {
                value 2;
            }
            enum seven {
                value 7;
            }
            enum eight {
                value 8;
            }
        }
        default seven;
    }
    
 Yang used for testing:

    module enum-default-test {
    namespace urn:x;
    prefix x;
    leaf myenum {
        type enumeration {
            enum zero;
            enum one;
            enum two {
                value 2;
            }
            enum seven {
                value 7;
            }
            enum eight {
                value 8;
            }
        }
        default seven;
    }
    leaf mybytes {
        type enumeration {
            enum 4k;
            enum 8k {
                value 8192;
            }
            enum 12k {
                value 12288;
            }
            enum 16k {
                value 16384;
            }
        }
        default 16k;
    }
}

**Comment by dhubler** [comment]
should be fixed on master, thank you!
