### ISSUE TITLE
Yang loading fails if 'mandatory' substatement is present under 'choice' statement

### ISSUE THREAD

**Issue by davidmat50** [freeconf/gconf#44]
Yang loading fails if 'mandatory' substatement is present under 'choice' statement.

https://www.rfc-editor.org/rfc/rfc7950#section-7.9.4
As per RFC 7950, mandatory statement should be supported for choice

Yang model used for testing is below.

	module choice-mandatory-test {
    namespace urn:x;
    prefix x;
    container transfer {
        choice how {
            mandatory true;
            case interval {
                leaf interval {
                    type uint16;
                }
            }
            case daily {
                leaf daily {
                    type empty;
                }
            }
            case manual {
                leaf manual {
                    type empty;
                }
            }
        }
    }

**Comment by dhubler** [comment]
fixed
