### ISSUE TITLE
Resolving of the "uses" is incorrect when  nested "uses" is used in the yang

### ISSUE THREAD

**Issue by davidmat50** [freeconf/gconf#46]
**Problem observed:**
 when  a 'grouping' has "uses"  and when that same grouping was attached  to a module using another 'uses',   then we observe that the incorrect grouping gets attached to the module. 

Example yang files used are shown below:    
**Test-common-module.yang** 

	module Test-common-module {
		yang-version "1.1";
		prefix common1;
		namespace urn:x;

		description
		  "Common types";

		grouping limit {
			leaf rate {
				type uint64;
			}
		}

		grouping profile {
			leaf peak-rate {
				type uint32;
			}

			container profile-limit {
				uses common1:limit;
			}
		}
	}

**Test-policy.yang:**

	module Test-policy {
		yang-version 1.1;
		prefix policy;
		namespace urn:x;

		import Test-common-module {
			prefix common1;
		}

		container policy {
			description
			  "Policy rules";
			list rules {
				key "id";
				unique "name";

				leaf id {
					type string{
						length "5..36";
					}
				}

				leaf name {
					type string {
						length "5..255";
					}
				}

				container a-profile {
					uses common1:profile;
					leaf traffic-type {
						type string;
					}
				}
			}
		}
	}

**Now when we load the Test-policy  module,   the loading is successs,  but while resolving the  "uses common1:limit"  in Test-common-module,  the datadefinitions for  "grouping profile" gets attached instead of  attaching datadefinitions for  "grouping limit" .**

This is resulting in "grouping profile "  getting attached unlimited times recursilvely .Due to this while iterating through the datadefinitions of "a-profile" , it  results in unlimited iterations counts  of  'peak-rate'  and 'profile-limit'  recursively

Please fix.

**Please note**: such issues are not seen when only one direct "uses"  is resolved.   mainly seen when nested "uses" is present in yang.

**Comment by dhubler** [comment]
fixed
