### ISSUE TITLE
Module description is not as expected if submodules are included.

### ISSUE THREAD

**Issue by davidmat50** [freeconf/gconf#50]
If we include submodules into the main yang module,   the main module description fecthed using Description() method is returning the description of the last included submodule.  I was expecting the description of the main module itself as  returned value.

Example: 
**Main module (module_core.yang):**

	module module_core {

		namespace "urn:params:module_core";
		prefix module_core;
		yang-version 1.1;

		include submodule_1;
		include submodule_2;
		description
		  "This is main module core";

		container testing {
			description
			  "testing container in main module";
			leaf cont1 {
				type string;
			}
			leaf cont2 {
				type int32;
			}
		}
	}		

**Submodule 1 submodule_1.yang:**

	submodule submodule_1 {

		yang-version 1.1;

		belongs-to "module_core" {
			prefix "module_core";
		}
		description
		  "Submodule-1 with list";

		list root-list-submodule1 {
			leaf leaf-A {
				type string;
				default "Success";
			}
			leaf leaf-B {
				type new-type-submodule2;
			}
			uses the_only_group;
		}

		grouping the_only_group {
			leaf leaf-from-group {
				type new-type-submodule2;
			}
			leaf-list leaf-list-from-group {
				type string;
				default "ok";
			}
		}
	}		
	
	
**submodule 2 submodule_2.yang:**

	submodule submodule_2 {

		yang-version 1.1;

		belongs-to "module_core" {
			prefix "module_core";
		}
		description
		  "Submodule-2 with typedef";

		typedef new-type-submodule2 {
			description
			  "New type definition";
			type uint16 {
				range "10 .. 2000";
			}
			default 100;
			units parrots;
		}
	}		

**In the above example, after loading  module_core, i was expecting   module.Description()  to return "This is main module core" , but instead ,  it is returning "Submodule-2 with typedef"**

**Comment by dhubler** [comment]
I was able to easily verify this and investigate the issue.  From my
initial investigation, the resolution might require maybe a week or so to
resolve.  Currently submodules just use the parent Module object and not
only does this clobber description, it doesn't properly honor prefix
handling and there are likely other issues.

**Comment by dhubler** [comment]
I created a branch called issue-50-submodules which should solve your issue, but that i need to perform more tests on and likely resolve more issue related to submodules before I merge to master

**Comment by davidmat50** [comment]
Thank you for providing the fix in a seperate branch for the issue i reported.  Anyway i will wait for the complete fix in the master branch  which may have other extended fixes for potential issues related to submodules. 

Thank you.

**Comment by dhubler** [comment]
fixed
