### ISSUE TITLE
"Import" of  a module is not proper when "include" being done.

### ISSUE THREAD

**Issue by davidmat50** [freeconf/gconf#52]
After  https://github.com/freeconf/yang/issues/50  ,    the normal import of another yang module to a yang module works,  but 
the importing of the an external module fails when the import is done on a module which was being included.   The loading of the yang itself fails 

Example  below:
loading error was :   "module not found imp"

module_core yang:

	module module_core {
		
		namespace "urn:params:module_core";
		prefix module_core;
		yang-version 1.1;
		
		include submodule_1;

	}	

submodule_1 yang

	submodule submodule_1 {

		yang-version 1.1;

		belongs-to "module_core" {
			prefix "module_core";
		}

		import module_for_import {
			prefix imp;
		}

		description
		  "Submodule with container";

		container root-from-submodule1 {
			leaf leaf-A {
				type string;
				default "Success1";
			}
			leaf leaf-B {
				type imp:new-type-from-module;
			}
		}
	}	

module_for_import yang:

	module module_for_import {

		namespace "urn:params:module_for_import";
		prefix imp;
		yang-version 1.1;

		typedef new-type-from-module {
			description
			  "New type definition";
			type uint16 {
				range "10 .. 2000";
			}
			default 100;
			units parrots;
		}
	}

The error  is :
 **module not found imp**

**Comment by dhubler** [comment]
fixed  (had issue # wrong in comment)
https://github.com/freeconf/yang/commit/9597c31dbe2016c696b223026edba028928eafa2
