### ISSUE TITLE
Issue in referencing definitions from the same module  when using submodules. 

### ISSUE THREAD

**Issue by davidmat50** [freeconf/gconf#54]
Prior to https://github.com/freeconf/yang/issues/50,  the yang files  mentioned below were getting loaded succesfuly without any errors.    But after https://github.com/freeconf/yang/issues/50,    the following error is thrown.

_**module_core/submodule_1/root-list-submodule1/leaf-B - typedef new-type-submodule2 not found**_

As per RFC7950 section  ,   When an external module referece from an imported module is used, then  we must use prefix followed by ":" , BUT  If there are  references to definitions in the same local module or submodules ,  then it is not mandatory that we use prefix followed by ": "   to refer to local referecnes within the module of submodule.   We  MAY or MAY  NOT use ":"  .   So, in case of included submodules,  we should support  referencing  in both ways by a) by using ";"  and  b)  without using ":'  

![image](https://github.com/freeconf/yang/assets/11210436/0c5cf12a-6eb9-44a2-854c-5762ab1b9684)

**Previous to  https://github.com/freeconf/yang/issues/50, we were able to  load below yang files  succesfully.  Is it possible to maintain the same behaviour now too?** 

module_core.yang

	module module_core {
		
		namespace "urn:netcracker:params:module_core";
		prefix module_core;
		yang-version 1.1;
		description "This is main Module";
		
		include submodule_1;
		include submodule_2;

	}		

submodule1.yang

	submodule submodule_1 {
		
		yang-version 1.1;
		description "Submodule-1 with list";
		belongs-to "module_core" {
			prefix "module_core";
		}
		
		list root-list-submodule1 {
			leaf leaf-A {
				type string;
				default "Success";
			}
			leaf leaf-B {
				type new-type-submodule2;
			}
			uses the_only_group; 
		}
		
		grouping the_only_group {
			leaf leaf-from-group {
				type new-type-submodule2;
			}
			leaf-list leaf-list-from-group {
				type string;
				default "ok";
			}
		}
	}		

submodule2.yang

	submodule submodule_2 {
		
		yang-version 1.1;
		description "Submodule-2 with typedef";
		belongs-to "module_core" {
			prefix "module_core";
		}

		typedef new-type-submodule2 {
			description "New type definition";
			type uint16 {
				range "10 .. 2000";
			}
			default 100;
			units parrots;
		}
	}

**Comment by dhubler** [comment]
I'm taking a look

**Comment by dhubler** [comment]
i found the problem, hopefully this will work for you
 https://github.com/freeconf/yang/commit/ba7fb8862475a2b2a1a9f81dd7cace615046e295
