### ISSUE TITLE
loading fails if double quotes used after identity-base and identityref-base

### ISSUE THREAD

**Issue by davidmat50** [freeconf/gconf#56]
In the exmaple given in  RFC 7950  sections  https://www.rfc-editor.org/rfc/rfc7950.html#section-7.18.3   and  https://www.rfc-editor.org/rfc/rfc7950.html#section-9.10.5 ,  double quotes were  after the base statement. 
But if i try the same,  the yang loading fails.   However, if we remove the double quotes,    the yang file laoding is succsessful.  
Please check and make it to be in sync with RFC. 

Exmaple file:

identity1.yang

    module identity1 {
       yang-version 1.1;
       namespace "urn:example:my-crypto";
       prefix mc;

       import example-crypto-base {
         prefix "crypto";
       }

       identity aes {
         base "crypto:crypto-alg";
       }

       leaf crypto {
         type identityref {
           base "crypto:crypto-alg";
         }
       }
     }
     
     
example-crypto-base.yang 

	module example-crypto-base {
		   yang-version 1.1;
		   namespace "urn:example:crypto-base";
		   prefix "crypto";

		   identity crypto-alg {
			 description
			   "Base identity from which all crypto algorithms
				are derived.";
		   }

		   identity symmetric-key {
			 description
			   "Base identity used to identify symmetric-key crypto
				algorithms.";
			 }

		   identity public-key {
			 description
			   "Base identity used to identify public-key crypto
				algorithms.";
			 }
		 }

**Comment by dhubler** [comment]
fixed identity/base, but looking at RFC i wonder if `uses` should follow suit.  The ABNF is not clear here. Do you know?
