### ISSUE TITLE
yang loading failing for 'anydata' statement,   if any of its susbstatments coexist with 'descrition' substatement

### ISSUE THREAD

**Issue by davidmat50** [freeconf/gconf#57]
Refer to below exmaple: 
If only 'description' susbstatment present under anydata, yang loading is succesfull
if only 'when' substatment is present under anydata, yang loading is succesful. 
if both 'description' and 'when' substatements are present under anydata, then yang loading is failing. 
No other substatements are being able to be co-exist alomg with 'description'

	module anydataTest {
		namespace urn:x;
		prefix x;
		revision 2023-01-01;
		leaf leaf-node {
			type string;
		}
		container Test {
			anydata dump {
				when "../../leaf-node";               
				description "Dump data";  
			}
		}
	}

**Comment by dhubler** [comment]
fixes
