### ISSUE TITLE
Multiple 'default' subsatements for leaf-list

### ISSUE THREAD

**Issue by davidmat50** [freeconf/gconf#58]
As per RFC7950 , a leaf-list can have more than  one (0..n)  'default' substatements 
( if 'min-elements'  with  values 1 or more is not present in the leaf-list)  

The freeconf/yang library provides a method  Default() for leaf, leaflist etc..
But as lieaf-list can have (0..n) deafults,  is there any possibility of  providing an additional  method to get mutiple default values for leaf-list case??
something like  ->   func (m *LeafList) Defaults() []interface{}   ??????

**Comment by dhubler** [comment]
fixed.  Defaults() still returns an "interface{}" but underlying type is always a "[]interface{}"
