### ISSUE TITLE
Issue in fetching 'unique' for list

### ISSUE THREAD

**Issue by davidmat50** [freeconf/gconf#59]
Yang file with a 'list' statement and 'unique' susbstatement  was laoded succesfully. But the  method to fetch the unique()  info was NOT returning any valid values. 

func (m *List) Unique() [][]string 

Tested yang:  listUniqueTest

	module listUniqueTest {
		namespace urn:x;
		prefix x;
		revision 2023-01-01;
		list user {
			//key "name employee-id";
			unique "employee-id full-name";
			leaf name {
				type string;
			}
			leaf employee-id {
				type uint32;
			}
			leaf full-name {
				type string;
			}
			leaf class {
				type string;
				mandatory true;
			}
			description "Employee Information";
		}
	}

**Comment by dhubler** [comment]
fixed
