### ISSUE TITLE
Trouble with UnionList format

### ISSUE THREAD

**Issue by HRogge** [freeconf/gconf#60]
I have a slice of IP addresses in one of my yang models, based on the IETF IP definition (which is a union of an IPv4 and an IPv6 pattern). Could it be that the UnionList handling is missing in the node/value.go NewNode() function?

**Comment by HRogge** [comment]
I think I have part of a solution in #62 (works for reading out of the model), but I am not sure how the testcases for node/value.go work.

**Comment by dhubler** [comment]
i added a test and your code looked great so i merged it into master.
