### ISSUE TITLE
Augmented data is missing  in data definition

### ISSUE THREAD

**Issue by davidmat50** [freeconf/gconf#61]
After the fix https://github.com/freeconf/yang/issues/55 , it looks like augmented data is missing in the data definitions of the module.

Example, 
aug-main.yang 

	module aug-main {
		yang-version "1.1";
		namespace "urn:params:custom";
		prefix custom;

		import aug-common {
			prefix common;
			revision-date 2020-02-04;
		}

		description
		  "Augment tes main file";

		revision 2020-02-04 {
			description
			  "initial draft";s
		}

		leaf test {
			type int8;
		}

		augment "/common:interfaces/common:ifEntry" {
			when "common:ifIndex = 1";
			leaf ds0ChannelNumber {
				type uint8;
			}
		}
	}

aug-common.yang

	module aug-common {
		yang-version "1.1";
		namespace "urn:params:common";
		prefix common;

		description
		  "Augment common test file";
		revision 2020-02-04 {
			description
			  "initial draft";
		}

		container interfaces {
			list ifEntry {
				key "ifIndex";
				
				leaf ifIndex {
					type uint32;
				}
				leaf ifDescr {
					type string;
				}
				leaf ifMtu {
					type int32;
				}
			}
			container something {
				leaf a1 {
					type int8;
				}
			}
		}
	}

In the above exmaple, i was expecting the data definition in module structure would be having ifEntry, which is the augmented data, but it was missing

**Comment by dhubler** [comment]
Good news, this "fix" was intentional so I can easily revert it.  Bad news is I may still not have an understanding of augment.  In this example you are augmenting a definition you never "use".  To that point, I don't understand the point of augmenting anything from imported modules that are not groupings because groupings are the only way to add imported definitions into a module AFAIU.

**Comment by davidmat50** [comment]
Not really.    Grouping are NOT the only way add imported definitions into module.

Augment is used to add an existing model (probabaly a standard model) , into our yang module and also additionally add some extra nodes along with it.  The target node of augment cannot be endings nodes like leaf, leaf-list etc.   The target node of augment can accomodate more data nodes internally ( eg like container,  list, choice etc) .    Then,   we can add additional nodes  as substatements of  augment statement.    

If a when condition is present as substament of augment,  it is applcicable to the additional nodes under augment . It indicates that  the new/additional nodes are valid to be added in the yang instance only if the condition is satisfied 

Refernce: https://www.rfc-editor.org/rfc/rfc7950.html#section-4.2.8 , 

Grouping is a resuable set/collection  of data nodes which can be instantiated using 'uses' .
We can use  "uses"  under augment  if we need to add all the nodes in grouping  along with the augment, 
But it is not necessary to use "uses" under augment always. 


In the example i have given above, the   leaf  "ds0ChannelNumber"  is an additional node under the ifEntry list , and it can present in the yang data instance only if the condition  "common:ifIndex = 1";  is satisfied. 
The same exmaple is seen in  https://www.rfc-editor.org/rfc/rfc7950.html#section-7.17.3

The previous behaviour of  implemnation prior to https://github.com/freeconf/yang/issues/55  was  observred  as i explained above. The issue i obsrved there was that  i was not able to use "uses"  under augment. 

Hope  this will help.

**Comment by dhubler** [comment]
What I find confusing in RFC Section 4.2.8:

"   The "augment" statement defines the location in the data model
   hierarchy **where** new nodes are inserted....

It does not mention inserting the nodes **AND** include a copy of the target where the augment statement is declared.  I'm happy to be wrong about this.

**Comment by dhubler** [comment]
here are some links that seem to support my understanding, but I admit do not explicitly discount your understanding:

https://1.ieee802.org/yangsters/yang-examples/yang-augment-example/

https://stackoverflow.com/questions/64464507/how-to-augment-list-from-one-module-to-another-and-add-leafs-yang

**Comment by davidmat50** [comment]
yeah.  I see. 
I was also having a wrong understanding.
It seems augmenting of additional nodes should happen into the target location's data tree  , and  target nodes's data tree not needed to be copied to the place where augment statement is declared.   OK got it.
