### ISSUE TITLE
Config set to false,  but does not take complete effect

### ISSUE THREAD

**Issue by davidmat50** [freeconf/gconf#63]
As per https://www.rfc-editor.org/rfc/rfc7950.html#section-7.21.1
   If a node has "config" set to "false", no node underneath it can have
   "config" set to "true".

Currently  
Config()  method is returning true if no config is mentioned for the data node - This is OK.
Config() method is returning false for the node if any of parent/grand parents  is marked with config as "false" - This is OK. 
Config() method is returning true if  a node is marked config=true and any of its parent or grand parent nodes is marked false.  - This is not OK. 

As per RFC, If a node has "config" set to "false", no node underneath it can have config set to true. In such cases i feel the yang loader should throw error as it is invalid yang. 

eg files:

	module container-config {
		namespace urn:x;
		prefix x;
		revision 2020-01-01;
		leaf dummy {
			type uint16;
		}
		container car {
			description "This is the description of container";
			config false;
			leaf name {
				type string;
				mandatory true;
			}
			leaf year {
				type string;
				mandatory true;
			}
			leaf color {
				type string;
			}
			list engine {
				config true;
				leaf horse-power {
					type uint16;
				}
				leaf-list seat-type {
					type string;
				}
			}
		}
	}
	
	
In this exmaple car's config was false.   but engin's config was marked as "true" which is against the rules.  But yang loading was succesful and config() method for engine  returned true.

**Comment by dhubler** [comment]
fixed
