### ISSUE TITLE
case substatemnt not supported for augment  

### ISSUE THREAD

**Issue by davidmat50** [freeconf/gconf#64]
Two isses seen
1.  Not able to add augment's target location as a choice. 
2. Not able to add case substatment under augment-  But RFC950 supports it. 

exmple files:

file used to load:  aug-common-includes.yang

	module aug-common-includes {
		yang-version "1.1";
		namespace "urn:params:common";
		
		include aug-common-sub;
		include aug-main-sub;
	}

aug-main-sub.yang

	submodule aug-main-sub {
		yang-version "1.1"; 
		namespace "urn:params:custom";

		belongs-to "common-includes" {
			prefix "common-includes";
		}
		prefix custom;

		leaf test {
			type int8;
		}

		augment "/modification/mod-info/mod-choice" {
			case null-handle {
				leaf null-handle {
				   type empty;
				   description
					  "null-handle";
				}
			 }
		}
	}

aug-common-sub.yang

	submodule aug-common-sub {
		yang-version "1.1";
		namespace "urn:params:common";
		prefix common;

		belongs-to "common-includes" {
			prefix "common-includes";
		}

		container modification {
			container mod-info {
				leaf a1 {
					type int8;
				}

				choice mod-choice {
					description "mod-choice";
					case wildcard {
						leaf wildcard {
							type empty;
							description
								"wildcard";
						}
					}

					case stream-handle {
						leaf stream-handle {
							type empty;
							description
								"stream-handle";
						}
					}
				}
			}
		}
	}

**Comment by dhubler** [comment]
fixed
