### ISSUE TITLE
Yang loader gets blocked for for an invalid yang file. 

### ISSUE THREAD

**Issue by davidmat50** [freeconf/gconf#68]
When an invalid yang file is tried to be loaded, it just hangs and does not throw any proper error.

The file used is shown below.  The yang syntax got corrupted  due to improper commenting .
in such cases, it was expected that Loader() will  throw errror, but it was not. 

	module basic_choices {
		
		namespace "urn:params:basic_choices";
		prefix basic_choices;
		

		container root-container {
		
			choice explicit-cases {
				/*mandatory true*;/
				case explicit-case-A {
					leaf leaf-A {
						type int8;
					}
					leaf-list leaf-list-A {
						type uint8;
					}
				}
				case explicit-case-B {
					container container-B {
						leaf leaf-BB {
							type string;
							}
						}
					list list-B {
						leaf leaf-BBB {
							type string;
						}
					}
				}
			}
		}
	}

**Comment by dhubler** [comment]
fixed
