### ISSUE TITLE
Fraction-digits is not inherited through typedef

### ISSUE THREAD

**Issue by raghavendramayagundi** [freeconf/gconf#81]
For the below yang sample:
`typedef new_type_decimal {
		type decimal64 {
			fraction-digits 4;
			range "-11.111 .. 22.222" {
					error-message "This is an error-message for range in typedef";
				}
		}
		description "This is new_type_decimal";
	}
leaf leaf-derived-type {
			type new_type_decimal;
			description "This is leaf-derived-type";
		}`

Type.FractionDigits() returns 0 instead of 4. Looks like need to add deriving of fraction-digits to mixin(derived *Type).

I am using the master branch v0.0.0-20230804003402-7593854e7f4d

**Comment by dhubler** [comment]
little behind, but i'll take a look in next few days

**Comment by dhubler** [comment]
fixed
