### ISSUE TITLE
Panic when 'config:true' is added inside a choicecase in yang

### ISSUE THREAD

**Issue by davidmat50** [freeconf/gconf#83]
This is in continuation to  https://github.com/freeconf/yang/issues/74

only one yang file mentioned in https://github.com/freeconf/yang/issues/74  loads succesfully. the other one panics.

file:  basic_config2.yang

	module basic_config2 {

		namespace "urn:params:basic_config";
		prefix basic_config;
		
		yang-version 1.1;

			
		container root-container {
			leaf leaf-init {
				description "This is a leaf with config false";
				type boolean;
				default true;
				units USD;
			}
		
			choice choice-init {
				description "This is a choice with config false";
				default case-A;
				case case-A {
					leaf leaf-init1 {
						type string;
						config true;
					}
				}
				case case-B {
					leaf leaf-init2 {
						type string;
					}
				}
			}
		}
	}

**Comment by dhubler** [comment]
little behind, but i'll take a look in next few days

**Comment by dhubler** [comment]
fixed
